/**
 * Seed demo catalog for ALQAIRA — sections, style categories and sample
 * products with size variants. Idempotent: categories upsert by slug, products
 * skip if their slug already exists.
 *
 *   node scripts/seedDemoData.js
 *
 * Product/category images come from /products/ai/<key>-N.jpg — professional
 * watermarked images generated by scripts/generate_catalog.py. Replace with real
 * product photography from the admin panel before going live.
 */
import mongoose from "mongoose";
import { env } from "../src/config/env.js";
import { CategoryModel } from "../src/modules/category/category.model.js";
import { ProductModel } from "../src/modules/product/product.model.js";
import { SettingsModel } from "../src/modules/settings/settings.model.js";

// Main categories per section (no sub-categories). `imgKey` picks the category
// card image from /products/ai. Regional thobe styles live as products inside
// "Thobe & Jubbas".
const CATEGORIES = [
  // Men
  {
    name: "Thobe & Jubbas",
    slug: "thobe-jubba",
    section: "men",
    isFeatured: true,
    displayOrder: 1,
    imgKey: "saudi",
    description: "Premium thobes and jubbas — Saudi, Omani, Emirati, Moroccan and designer styles.",
  },
  {
    name: "Pathani Suit",
    slug: "pathani-suit",
    section: "men",
    isFeatured: true,
    displayOrder: 2,
    imgKey: "pathani",
    description: "Rugged Pathani suits with a structured collar and side pockets.",
  },
  {
    name: "Kurta Pajama",
    slug: "kurta-pajama",
    section: "men",
    isFeatured: true,
    displayOrder: 3,
    imgKey: "straight",
    description: "Timeless straight-cut kurta with matching pajama.",
  },
  {
    name: "Jacket",
    slug: "jacket",
    section: "men",
    displayOrder: 4,
    imgKey: "jacket",
    description: "Ethnic jackets and bandhgalas to layer over a kurta or thobe.",
  },
  // Women
  {
    name: "Abayas",
    slug: "abaya",
    section: "women",
    isFeatured: true,
    displayOrder: 1,
    imgKey: "women",
    description: "Elegant, breathable abayas made from premium fabric.",
  },
  // Kids & Boys
  {
    name: "Thobe & Jubbas",
    slug: "kids-thobe-jubba",
    section: "kids",
    isFeatured: true,
    displayOrder: 1,
    imgKey: "kids-saudi",
    description: "Premium thobes and jubbas for boys, in kids' sizes.",
  },
  {
    name: "Pathani Suit",
    slug: "kids-pathani-suit",
    section: "kids",
    isFeatured: true,
    displayOrder: 2,
    imgKey: "kids-pathani",
    description: "Pathani suits for boys with a structured collar and side pockets.",
  },
  {
    name: "Kurta Pajama",
    slug: "kids-kurta-pajama",
    section: "kids",
    isFeatured: true,
    displayOrder: 3,
    imgKey: "kids-straight",
    description: "Straight-cut kurta with matching pajama, in boys' sizes.",
  },
];

const SIZES_MEN = ["S", "M", "L", "XL", "2XL", "3XL"];
const SIZES_WOMEN = ["S", "M", "L", "XL", "2XL"];
const SIZES_KIDS = ["2-3Y", "4-5Y", "6-7Y", "8-9Y"];

const FABRICS = ["Premium Japan Fabric", "Soft Cotton Blend", "Light Linen", "Nida Crepe"];
const COLORS = ["Off White", "Beige", "Sand", "Navy", "Charcoal", "Olive"];

/** /products/ai/<key>-<n>.jpg (n = 1..3) — watermarked, faceless-mannequin
 * images generated by scripts/generate_catalog.py. */
function aiImg(key, n) {
  return `/products/ai/${key}-${n}.jpg`;
}

function makeVariants(sizes, base) {
  return sizes.map((size, i) => ({
    size,
    stock: base + i * 3,
    sku: `${size}-${Math.floor(1000 + i * 137)}`,
  }));
}

// Products per category — each picks its own image set (img → /products/ai/<img>).
const PRODUCTS_BY_CATEGORY = {
  "thobe-jubba": [
    { name: "Riyadh Classic Thobe", img: "saudi" },
    { name: "Najdi Premium Thobe", img: "saudi" },
    { name: "Royal Saudi Jubba", img: "saudi" },
    { name: "Muscat Dishdasha", img: "omani" },
    { name: "Nizwa Tassel Jubba", img: "omani" },
    { name: "Dubai Signature Kandura", img: "emirati" },
    { name: "Abu Dhabi Pocket Kandura", img: "emirati" },
    { name: "Marrakech Kaftan", img: "moroccan" },
    { name: "Fez Embroidered Jubba", img: "moroccan" },
    { name: "Noir Tailored Jubba", img: "designer" },
    { name: "Onyx Modern Thobe", img: "designer" },
  ],
  "pathani-suit": [
    { name: "Khyber Pathani Suit", img: "pathani" },
    { name: "Frontier Pathani Set", img: "pathani" },
  ],
  "kurta-pajama": [
    { name: "Ivory Straight Kurta Set", img: "straight" },
    { name: "Cotton Comfort Kurta Set", img: "straight" },
  ],
  jacket: [
    { name: "Classic Nehru Jacket", img: "jacket" },
    { name: "Royal Bandhgala Jacket", img: "jacket" },
  ],
  abaya: [
    { name: "Layla Flared Abaya", img: "women" },
    { name: "Noor Premium Abaya", img: "women" },
    { name: "Dana Embroidered Abaya", img: "women" },
  ],
  "kids-thobe-jubba": [
    { name: "Little Najdi Thobe", img: "kids-saudi" },
    { name: "Junior Riyadh Thobe", img: "kids-saudi" },
    { name: "Little Muscat Dishdasha", img: "kids-omani" },
    { name: "Junior Dubai Kandura", img: "kids-emirati" },
    { name: "Little Marrakech Kaftan", img: "kids-moroccan" },
    { name: "Junior Noir Jubba", img: "kids-designer" },
  ],
  "kids-pathani-suit": [{ name: "Junior Khyber Pathani Set", img: "kids-pathani" }],
  "kids-kurta-pajama": [{ name: "Little Ivory Kurta Set", img: "kids-straight" }],
};

async function run() {
  console.log("Connecting to MongoDB...");
  await mongoose.connect(env.MONGODB_URI);
  console.log("Connected.\n");

  // Migration: "Burkha" was renamed to "Abaya" — remove the old category and
  // the one product whose slug still carried the old name.
  // Cleanup: remove any old categories (and their products) that are no longer
  // part of the current structure — e.g. the old per-region jubba categories.
  const keepSlugs = CATEGORIES.map((c) => c.slug);
  const stale = await CategoryModel.find({ slug: { $nin: keepSlugs } });
  for (const s of stale) {
    await ProductModel.deleteMany({ category: s._id });
    await CategoryModel.deleteOne({ _id: s._id });
  }
  if (stale.length) console.log(`[CLEAN] Removed ${stale.length} old categories + their products`);

  // Ensure settings exist
  const settingsExists = await SettingsModel.findOne();
  if (!settingsExists) {
    await SettingsModel.create({});
    console.log("[OK]   Created default settings");
  }

  // Upsert categories
  const catBySlug = {};
  for (const c of CATEGORIES) {
    const { imgKey, ...catDoc } = c;
    const cat = await CategoryModel.findOneAndUpdate(
      { slug: c.slug },
      { $set: { ...catDoc, image: aiImg(imgKey, 1), isActive: true } },
      { new: true, upsert: true },
    );
    catBySlug[c.slug] = cat;
    console.log(`[OK]   Category: ${c.name} (${c.section})`);
  }

  // Products
  let created = 0;
  for (const [slug, items] of Object.entries(PRODUCTS_BY_CATEGORY)) {
    const cat = catBySlug[slug];
    const sizes =
      cat.section === "women" ? SIZES_WOMEN : cat.section === "kids" ? SIZES_KIDS : SIZES_MEN;
    for (let i = 0; i < items.length; i++) {
      const { name, img } = items[i];
      const productSlug = name
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, "-")
        .replace(/(^-|-$)/g, "");
      const images = [1, 2, 3].map((n) => aiImg(img, n));
      const existing = await ProductModel.findOne({ slug: productSlug });
      if (existing) {
        // Refresh images, category link AND size variants (S..3XL) on existing
        // products so old image paths and old sizes (XXL) get updated.
        existing.images = images;
        existing.category = cat._id;
        existing.categoryName = cat.name;
        existing.variants = makeVariants(sizes, 8 + i);
        await existing.save();
        console.log(`[UPD]  Refreshed: ${name}`);
        continue;
      }
      const price = 1499 + Math.floor(Math.random() * 30) * 100;
      const compareAtPrice = price + 600 + Math.floor(Math.random() * 10) * 100;
      await ProductModel.create({
        name,
        slug: productSlug,
        shortDescription: `${name} — ${cat.name} made from premium fabric.`,
        description: `${name} from ALQAIRA's ${cat.name} collection. ${cat.description} Made from ${FABRICS[i % FABRICS.length]} for a comfortable, all-day fit. Clean stitching and a neat finish — simple, stylish clothing made to last.`,
        category: cat._id,
        categoryName: cat.name,
        section: cat.section,
        price,
        compareAtPrice,
        images,
        variants: makeVariants(sizes, 8 + i),
        fabric: FABRICS[i % FABRICS.length],
        color: COLORS[i % COLORS.length],
        careInstructions: "Dry clean recommended. Cool iron. Do not bleach.",
        tags: [cat.section, slug, "premium"],
        rating: 0,
        numReviews: 0,
        isFeatured: i === 0,
        isNewArrival: i % 2 === 0,
        isActive: true,
      });
      created++;
      console.log(`[OK]   Product: ${name}  (₹${price})`);
    }
  }

  console.log(`\nDone. ${created} products created.`);
  await mongoose.disconnect();
}

run().catch(async (err) => {
  console.error("Seed failed:", err.message);
  await mongoose.disconnect();
  process.exit(1);
});
