/**
 * Seed demo catalog for ALQAIRA — sections, style categories and sample
 * products with size variants. Idempotent: categories upsert by slug, products
 * skip if their slug already exists.
 *
 *   node scripts/seedDemoData.js
 *
 * Product/category images come from /products/ai/<key>-N.jpg — professional
 * watermarked images generated by scripts/generate_catalog.py. Replace with real
 * product photography from the admin panel before going live.
 */
import mongoose from "mongoose";
import { env } from "../src/config/env.js";
import { CategoryModel } from "../src/modules/category/category.model.js";
import { ProductModel } from "../src/modules/product/product.model.js";
import { SettingsModel } from "../src/modules/settings/settings.model.js";

const CATEGORIES = [
  // Men — jubba & kurta styles
  {
    name: "Saudi Style Jubba",
    slug: "saudi-style-jubba",
    section: "men",
    isFeatured: true,
    displayOrder: 1,
    description: "Classic Saudi thobe silhouette with a crisp collar and clean placket.",
  },
  {
    name: "Omani Style Jubba",
    slug: "omani-style-jubba",
    section: "men",
    isFeatured: true,
    displayOrder: 2,
    description: "Collarless Omani dishdasha with the signature tassel (furakha).",
  },
  {
    name: "Emirati Style Jubba",
    slug: "emirati-style-jubba",
    section: "men",
    isFeatured: true,
    displayOrder: 3,
    description: "Refined Emirati kandura with a front pocket and minimal detailing.",
  },
  {
    name: "Moroccan / Kaftan Style Jubba",
    slug: "moroccan-kaftan-jubba",
    section: "men",
    isFeatured: true,
    displayOrder: 4,
    description: "Flowing Moroccan kaftan cut with ornate trims.",
  },
  {
    name: "Designer / Modern Style Jubba",
    slug: "designer-modern-jubba",
    section: "men",
    isFeatured: true,
    displayOrder: 5,
    description: "Contemporary tailored jubbas for the modern gentleman.",
  },
  {
    name: "Straight Cut Kurta Pajama",
    slug: "straight-cut-kurta-pajama",
    section: "men",
    displayOrder: 6,
    description: "Timeless straight-cut kurta with matching pajama.",
  },
  {
    name: "Pathani Kurta Pajama",
    slug: "pathani-kurta-pajama",
    section: "men",
    displayOrder: 7,
    description: "Rugged Pathani suit with a structured collar and side pockets.",
  },
  // Women
  {
    name: "Abaya",
    slug: "abaya",
    section: "women",
    isFeatured: true,
    displayOrder: 1,
    description: "Elegant, breathable abayas made from premium fabric.",
  },
  // Kids — same regional styles as men, tailored for little ones
  {
    name: "Kids Saudi Style Jubba",
    slug: "kids-saudi-jubba",
    section: "kids",
    isFeatured: true,
    displayOrder: 1,
    description: "Classic Saudi thobe silhouette with a crisp collar — sized for little ones.",
  },
  {
    name: "Kids Omani Style Jubba",
    slug: "kids-omani-jubba",
    section: "kids",
    isFeatured: true,
    displayOrder: 2,
    description: "Collarless Omani dishdasha with the signature tassel (furakha), in kids' sizes.",
  },
  {
    name: "Kids Emirati Style Jubba",
    slug: "kids-emirati-jubba",
    section: "kids",
    isFeatured: true,
    displayOrder: 3,
    description: "Refined Emirati kandura with minimal detailing, tailored for children.",
  },
  {
    name: "Kids Moroccan / Kaftan Style Jubba",
    slug: "kids-moroccan-kaftan-jubba",
    section: "kids",
    isFeatured: true,
    displayOrder: 4,
    description: "Flowing Moroccan kaftan cut with ornate trims, made for little ones.",
  },
  {
    name: "Kids Designer / Modern Style Jubba",
    slug: "kids-designer-modern-jubba",
    section: "kids",
    isFeatured: true,
    displayOrder: 5,
    description: "Contemporary tailored jubbas for the modern young gentleman.",
  },
  {
    name: "Kids Straight Cut Kurta Pajama",
    slug: "kids-straight-cut-kurta-pajama",
    section: "kids",
    displayOrder: 6,
    description: "Timeless straight-cut kurta with matching pajama, in kids' sizes.",
  },
  {
    name: "Kids Pathani Kurta Pajama",
    slug: "kids-pathani-kurta-pajama",
    section: "kids",
    displayOrder: 7,
    description: "Rugged Pathani suit with a structured collar and side pockets, for children.",
  },
];

const SIZES_MEN = ["S", "M", "L", "XL", "XXL"];
const SIZES_WOMEN = ["S", "M", "L", "XL"];
const SIZES_KIDS = ["2-3Y", "4-5Y", "6-7Y", "8-9Y"];

const FABRICS = ["Premium Japan Fabric", "Soft Cotton Blend", "Light Linen", "Nida Crepe"];
const COLORS = ["Off White", "Beige", "Sand", "Navy", "Charcoal", "Olive"];

/** Maps a category slug to its AI image set under /products/ai/<key>-N.jpg.
 * Generated (watermarked, faceless mannequin) by scripts/generate_catalog.py. */
const AI_KEY_BY_SLUG = {
  "saudi-style-jubba": "saudi",
  "omani-style-jubba": "omani",
  "emirati-style-jubba": "emirati",
  "moroccan-kaftan-jubba": "moroccan",
  "designer-modern-jubba": "designer",
  "straight-cut-kurta-pajama": "straight",
  "pathani-kurta-pajama": "pathani",
  abaya: "women",
  // Kids — each style has its own child-size image set
  "kids-saudi-jubba": "kids-saudi",
  "kids-omani-jubba": "kids-omani",
  "kids-emirati-jubba": "kids-emirati",
  "kids-moroccan-kaftan-jubba": "kids-moroccan",
  "kids-designer-modern-jubba": "kids-designer",
  "kids-straight-cut-kurta-pajama": "kids-straight",
  "kids-pathani-kurta-pajama": "kids-pathani",
};

function aiKey(slug, section) {
  if (section === "women") return "women";
  return AI_KEY_BY_SLUG[slug] || (section === "kids" ? "kids-saudi" : "saudi");
}

/** /products/ai/<key>-<n>.jpg (n = 1..3). */
function aiImg(key, n) {
  return `/products/ai/${key}-${n}.jpg`;
}

function makeVariants(sizes, base) {
  return sizes.map((size, i) => ({
    size,
    stock: base + i * 3,
    sku: `${size}-${Math.floor(1000 + i * 137)}`,
  }));
}

// title templates per category slug
const PRODUCTS_BY_CATEGORY = {
  "saudi-style-jubba": ["Riyadh Classic Thobe", "Najdi Premium Thobe", "Royal Saudi Jubba"],
  "omani-style-jubba": ["Muscat Dishdasha", "Nizwa Tassel Jubba"],
  "emirati-style-jubba": ["Dubai Signature Kandura", "Abu Dhabi Pocket Kandura"],
  "moroccan-kaftan-jubba": ["Marrakech Kaftan", "Fez Embroidered Jubba"],
  "designer-modern-jubba": ["Noir Tailored Jubba", "Onyx Modern Thobe", "Aristo Designer Jubba"],
  "straight-cut-kurta-pajama": ["Ivory Straight Kurta Set", "Cotton Comfort Kurta Set"],
  "pathani-kurta-pajama": ["Khyber Pathani Suit", "Frontier Pathani Set"],
  abaya: ["Layla Flared Abaya", "Noor Premium Abaya", "Dana Embroidered Abaya"],
  "kids-saudi-jubba": ["Little Najdi Thobe", "Junior Riyadh Thobe"],
  "kids-omani-jubba": ["Little Muscat Dishdasha"],
  "kids-emirati-jubba": ["Junior Dubai Kandura"],
  "kids-moroccan-kaftan-jubba": ["Little Marrakech Kaftan"],
  "kids-designer-modern-jubba": ["Junior Noir Jubba"],
  "kids-straight-cut-kurta-pajama": ["Little Ivory Kurta Set"],
  "kids-pathani-kurta-pajama": ["Junior Khyber Pathani Set"],
};

async function run() {
  console.log("Connecting to MongoDB...");
  await mongoose.connect(env.MONGODB_URI);
  console.log("Connected.\n");

  // Migration: "Burkha" was renamed to "Abaya" — remove the old category and
  // the one product whose slug still carried the old name.
  const oldBurkha = await CategoryModel.findOneAndDelete({ slug: "burkha" });
  if (oldBurkha) {
    await ProductModel.deleteMany({ category: oldBurkha._id });
    console.log("[CLEAN] Removed old Burkha category + its products");
  }
  await ProductModel.deleteOne({ slug: "noor-premium-burkha" });

  // Ensure settings exist
  const settingsExists = await SettingsModel.findOne();
  if (!settingsExists) {
    await SettingsModel.create({});
    console.log("[OK]   Created default settings");
  }

  // Upsert categories
  const catBySlug = {};
  for (const c of CATEGORIES) {
    const cat = await CategoryModel.findOneAndUpdate(
      { slug: c.slug },
      { $set: { ...c, image: aiImg(aiKey(c.slug, c.section), 1), isActive: true } },
      { new: true, upsert: true },
    );
    catBySlug[c.slug] = cat;
    console.log(`[OK]   Category: ${c.name}`);
  }

  // Products
  let created = 0;
  for (const [slug, names] of Object.entries(PRODUCTS_BY_CATEGORY)) {
    const cat = catBySlug[slug];
    const sizes =
      cat.section === "women" ? SIZES_WOMEN : cat.section === "kids" ? SIZES_KIDS : SIZES_MEN;
    for (let i = 0; i < names.length; i++) {
      const name = names[i];
      const productSlug = name
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, "-")
        .replace(/(^-|-$)/g, "");
      const images = [1, 2, 3].map((n) => aiImg(aiKey(cat.slug, cat.section), n));
      const existing = await ProductModel.findOne({ slug: productSlug });
      if (existing) {
        // Refresh images (and category link) on existing products so old/broken
        // image paths get replaced with the current AI catalog images.
        existing.images = images;
        existing.category = cat._id;
        existing.categoryName = cat.name;
        await existing.save();
        console.log(`[UPD]  Refreshed images: ${name}`);
        continue;
      }
      const price = 1499 + Math.floor(Math.random() * 30) * 100;
      const compareAtPrice = price + 600 + Math.floor(Math.random() * 10) * 100;
      await ProductModel.create({
        name,
        slug: productSlug,
        shortDescription: `${name} — ${cat.name} made from premium fabric.`,
        description: `${name} from ALQAIRA's ${cat.name} collection. ${cat.description} Made from ${FABRICS[i % FABRICS.length]} for a comfortable, all-day fit. Clean stitching and a neat finish — simple, stylish clothing made to last.`,
        category: cat._id,
        categoryName: cat.name,
        section: cat.section,
        price,
        compareAtPrice,
        images,
        variants: makeVariants(sizes, 8 + i),
        fabric: FABRICS[i % FABRICS.length],
        color: COLORS[i % COLORS.length],
        careInstructions: "Dry clean recommended. Cool iron. Do not bleach.",
        tags: [cat.section, slug, "premium"],
        rating: 0,
        numReviews: 0,
        isFeatured: i === 0,
        isNewArrival: i % 2 === 0,
        isActive: true,
      });
      created++;
      console.log(`[OK]   Product: ${name}  (₹${price})`);
    }
  }

  console.log(`\nDone. ${created} products created.`);
  await mongoose.disconnect();
}

run().catch(async (err) => {
  console.error("Seed failed:", err.message);
  await mongoose.disconnect();
  process.exit(1);
});
